config/routes.rb
Rails.application.routes.draw do
  root "groups#index"

  resources :groups do
    get :my, on: :collection
    resources :schedules, except: %i[new create destroy] do
      resources :lessons
    end
  end
  resources :subjects, only: [:edit, :update, :new, :create, :destory]
  resources :teachers, only: [:edit, :update, :new, :create, :destory]

  resources :lessons_changes

  resource :week_status, only: [] do
    post :toggle, on: :collection
  end

  resources :events, except: %i[show]
  resources :subscriptions, only: :create
  delete "/subscriptions", to: "subscriptions#destroy"

  get "profile", to: "users#show"
  get "profile/edit", to: "users#edit"
  patch "profile", to: "users#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :subscriptions, dependent: :destroy

  validates :title, presence: true
  validates :title, length: {minimum: 3}
  validates :description, length: {minimum: 30}
  validates :description, length: {maximum: 300}
end

app/models/group.rb
class Group < ApplicationRecord
  after_create :create_schedule
  has_many :schedules, dependent: :destroy
  has_many :lessons_changes, dependent: :destroy
  has_many :users, dependent: :nullify

  private

  def create_schedule
    (1..6).each do |week|
      Schedule.create(group: self, weeks_day: week)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :schedule
  belongs_to :subject
  belongs_to :teacher

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :number, uniqueness: {scope: :schedule_id}, unless: -> { adjacent }
  validates :schedule, presence: true
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validate :adjacent_lesson_uniqueness

  private

  def adjacent_lesson_uniqueness
    return unless adjacent? && schedule.lessons.where(number:, adjacent: true).exists?

    errors.add(:adjacent, "уже есть у урока")
  end
end

app/models/lessons_change.rb
class LessonsChange < ApplicationRecord
  belongs_to :subject
  belongs_to :teacher
  belongs_to :group

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validates :group, presence: true
  validates :group, uniqueness: {scope: [:number, :date]}

  before_validation :set_default_date, on: :create

  private

  def set_default_date
    self.date ||= Date.tomorrow
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, through: :user_roles
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  DAYS_OF_WEEK = {
    1 => "Понедельник",
    2 => "Вторник",
    3 => "Среда",
    4 => "Четверг",
    5 => "Пятница",
    6 => "Суббота"
  }.freeze

  belongs_to :group
  has_many :lessons, dependent: :destroy

  def wday
    DAYS_OF_WEEK[weeks_day]
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3

  belongs_to :group, optional: true
  has_many :subscriptions, dependent: :destroy
  has_many :user_roles
  has_many :roles, through: :user_roles

  def able_to_edit?(model)
    roles.map(&:name).include?(model.to_s)
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/week_status.rb
class WeekStatus < ApplicationRecord
end

app/controllers/lessons_changes_controller.rb
class LessonsChangesController < ApplicationController
  before_action :set_lessons_change, only: %i[show edit update destroy]

  # GET /lessons_changes
  def index
    date_param = params[:date]

    date = if date_param.present?
      Date.parse(date_param)
    elsif Time.zone.now.hour >= 12
      Date.tomorrow
    else
      Date.today
    end

    @lessons_changes = LessonsChange.where(date:).order(:group_id, number: :asc)
  end

  # GET /lessons_changes/new
  def new
    @lessons_change = LessonsChange.new
  end

  # GET /lessons_changes/1/edit
  def edit
  end

  # POST /lessons_changes
  def create
    @lessons_change = LessonsChange.new(lessons_change_params)

    if @lessons_change.save
      redirect_to lessons_changes_path, notice: "Изменение успешно создано."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lessons_changes/1
  def update
    if @lessons_change.update(lessons_change_params)
      redirect_to lessons_changes_path, notice: "Изменение успешно изменено."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lessons_changes/1
  def destroy
    @lessons_change.destroy
    redirect_to lessons_changes_url, notice: "Изменение успешно удалено."
  end

  private

  def authorization
    render_forbidden unless current_user&.able_to_edit?(:change)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_lessons_change
    @lessons_change = LessonsChange.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lessons_change_params
    params.require(:lessons_change).permit(:group_id, :number, :subject_id, :teacher_id, :room, :date)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_changes_helper.rb
module LessonsChangesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lessons_changes/_form.html.erb
<div class="row">
<div class="col-lg-7 col-xxl-5">
<%= form_with(model: lessons_change) do |form| %>
  <% if lessons_change.errors.any? %>
    <div style="color: red">
      <h2><%= lessons_change.errors.count %> ошибок:</h2>

      <ul>
        <% lessons_change.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :date, class:"form-label" %>
    <%= form.date_field :date, class:"form-control form-control-date", value: Date.tomorrow.to_s, min: Date.today.to_s %>
  </div>

  <div class="mb-3">
    <%= form.label :group_id, class:"form-label" %>
    <%= form.collection_select :group_id, Group.all, :id, :name, {}, { class: "form-select mb-1" } %>
    <%= link_to bi("plus-square"), new_group_path%>
  </div>

  <div class="mb-3">
    <%= form.label :number, class:"form-label" %>
    <%= form.number_field :number, class: "form-control", in: 1..7 %>
  </div>

  <div class="mb-3">
    <%= form.label :subject_id, class:"form-label" %>
    <%= form.collection_select :subject_id, Subject.all, :id, :name, {}, { class: "form-select mb-1" } %>
    <%= link_to bi("plus-square"), new_subject_path%>
  </div>

  <div class="mb-3">
    <%= form.label :teacher_id, class:"form-label" %>
    <%= form.collection_select :teacher_id, Teacher.all, :id, :name, {}, { class: "form-select mb-1" } %>
    <%= link_to bi("plus-square"), new_teacher_path%>
  </div>

  <div class="mb-3">
    <%= form.label :room, class:"form-label" %>
    <%= form.number_field :room, class: "form-control", in: 100..999 %>
  </div>

  <div class="mb-3">
    <%= form.submit t(".save"), class: "btn btn-primary"%>
  </div>
<% end %>
</div>
</div>

app/views/lessons_changes/_lessons_change.html.erb
<th><%= lessons_change.group.name %></th>
<th><%= lessons_change.number %></th>
<th><%= lessons_change.subject.name %></th>
<th><%= lessons_change.teacher.name %></th>
<th><%= lessons_change.room %></th>
<% if current_user&.able_to_edit?(:schedule) %>
  <th><%= link_to bi("pencil"), edit_lessons_change_path(id: lessons_change) %></th>
  <th><%= button_to bi("x-square text-danger"), lessons_change_path(id: lessons_change) , 
  method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')"%></th>
<% end %>

app/views/lessons_changes/edit.html.erb
<h1> <%= t(".name") %> </h1>

<%= render "form", lessons_change: @lessons_change %>

<br>

<div>
  <%= link_to t(".back"), lessons_changes_path %>
</div>

app/views/lessons_changes/index.html.erb
<h1>
  <%= t(".changes") %> 
  <% if current_user&.able_to_edit?(:change) %>
    <%= link_to bi("plus-square ms-2 text-primary"), new_lessons_change_path %>
  <% end %>
</h1>

<form id="date_form">
  <div class="row">
  <div class="col-5 col-lg-3">
  <input type="date" id="date_picker" name="date" value=<%= params[:date] || (Time.now.hour >= 20 ? Date.tomorrow : Date.today) %> class="mb-3 form-control form-control-date"/>
  </div>
  </div>
  <button type="submit", class="d-none btn btn-primary"><%= t(".show") %></button>
</form>

<%= javascript_include_tag 'date_picker', 'data-turbolinks-track': 'reload' %>

<div id="lessons_changes" class="card">
  <div class="card-body table-responsive">
    <table class="table table-responsive-md">
      <tr>
        <th><%= t('.group') %></th>
        <th><%= t('.lesson') %></th>
        <th><%= t('.subject') %></th>
        <th><%= t('.teacher') %></th>
        <th><%= t('.room') %></th>
        <% if current_user&.able_to_edit?(:schedule) %>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    <% @lessons_changes.each do |lessons_change| %>
      <tr><%= render lessons_change %></tr>
    <% end %>
    </table>
  </div>
</div>

app/views/lessons_changes/new.html.erb
<h1> <%= t(".name") %> </h1>

<%= render "form", lessons_change: @lessons_change %>

<br>

<div>
  <%= link_to t(".back"), lessons_changes_path %>
</div>

app/views/lessons_changes/show.html.erb
<%= render @lessons_change %>

<div>
  <%= link_to "Edit this lessons change", edit_lessons_change_path(@lessons_change) %> |
  <%= link_to "Back to lessons changes", lessons_changes_path %>

  <%= button_to "Destroy this lessons change", @lessons_change, method: :delete %>
</div>