config/routes.rb
Rails.application.routes.draw do
  root "groups#index"

  resources :groups do
    get :my, on: :collection
    resources :schedules, except: %i[new create destroy] do
      resources :lessons
    end
  end
  resources :subjects, only: [:edit, :update, :new, :create, :destory]
  resources :teachers, only: [:edit, :update, :new, :create, :destory]

  resources :lessons_changes

  resource :week_status, only: [] do
    post :toggle, on: :collection
  end

  resources :events, except: %i[show]
  resources :subscriptions, only: :create
  delete "/subscriptions", to: "subscriptions#destroy"

  get "profile", to: "users#show"
  get "profile/edit", to: "users#edit"
  patch "profile", to: "users#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :subscriptions, dependent: :destroy

  validates :title, presence: true
  validates :title, length: {minimum: 3}
  validates :description, length: {minimum: 30}
  validates :description, length: {maximum: 300}
end

app/models/group.rb
class Group < ApplicationRecord
  after_create :create_schedule
  has_many :schedules, dependent: :destroy
  has_many :lessons_changes, dependent: :destroy
  has_many :users, dependent: :nullify

  private

  def create_schedule
    (1..6).each do |week|
      Schedule.create(group: self, weeks_day: week)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :schedule
  belongs_to :subject
  belongs_to :teacher

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :number, uniqueness: {scope: :schedule_id}, unless: -> { adjacent }
  validates :schedule, presence: true
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validate :adjacent_lesson_uniqueness

  private

  def adjacent_lesson_uniqueness
    return unless adjacent? && schedule.lessons.where(number:, adjacent: true).exists?

    errors.add(:adjacent, "уже есть у урока")
  end
end

app/models/lessons_change.rb
class LessonsChange < ApplicationRecord
  belongs_to :subject
  belongs_to :teacher
  belongs_to :group

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validates :group, presence: true
  validates :group, uniqueness: {scope: [:number, :date]}

  before_validation :set_default_date, on: :create

  private

  def set_default_date
    self.date ||= Date.tomorrow
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, through: :user_roles
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  DAYS_OF_WEEK = {
    1 => "Понедельник",
    2 => "Вторник",
    3 => "Среда",
    4 => "Четверг",
    5 => "Пятница",
    6 => "Суббота"
  }.freeze

  belongs_to :group
  has_many :lessons, dependent: :destroy

  def wday
    DAYS_OF_WEEK[weeks_day]
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3

  belongs_to :group, optional: true
  has_many :subscriptions, dependent: :destroy
  has_many :user_roles
  has_many :roles, through: :user_roles

  def able_to_edit?(model)
    roles.map(&:name).include?(model.to_s)
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/week_status.rb
class WeekStatus < ApplicationRecord
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
  end

  # GET /groups/1
  def my
    @group = current_user.group
    @changes = LessonsChange.where(group: @group)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: "Группа успешно создана."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: "Группа успешно обновлена."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: "Группа успешно удалена."
  end

  private

  def authorization
    render_forbidden unless current_user&.able_to_edit?(:schedule)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def even_week?
    WeekStatus.first_or_create.even_week?
  end

  def bi(icon)
    "<i class=\"bi bi-#{icon}\"></i>".html_safe
  end

  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger if type == :alert
      type = :danger if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert alert-#{type} alert-dismissible fade show mt-3 #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw(""), :type => "button", :class => "btn-close", "data-bs-dismiss" => "alert", "aria-label" => "Close")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<div class="row">
<div class="col-lg-7 col-xxl-5">
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= group.errors.count %> ошибок:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit t(".save"), class: "btn btn-primary"%>
  </div>
<% end %>
</div>
</div>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <h3 class="text-center">
    <strong><%= t(".group")%>:</strong>
    <%= group.name %>
    <% if current_user&.able_to_edit?(:schedule) %>
      <%= link_to bi("pencil"), edit_group_path(id: group.id)%>
      <div class="btn-group" role="group">
      <%= button_to bi("x-square text-danger"), group_path(id: group.id), 
      method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')" %>
      </div>
    <% end %>
  </h3>

  <div class="row">
    <% group.schedules.each do |schedule| %>
      <%= render schedule %>
    <% end %>
  </div>
</div>

app/views/groups/_my_group.html.erb
<div id="<%= dom_id group %>">
  <h3 class="text-center">
    <strong><%= t(".group")%>:</strong>
    <%= group.name %>
    <% if current_user&.able_to_edit?(:schedule) %>
      <%= link_to bi("pencil"), edit_group_path(id: group.id)%>
      <div class="btn-group" role="group">
      <%= button_to bi("x-square text-danger"), group_path(id: group.id), 
      method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')" %>
      </div>
    <% end %>
  </h3>

  <div class="row">
    <% group.schedules.each do |schedule| %>
      <%= render "schedules/my_schedule", schedule: %>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<h1> <%= t(".name") %> </h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to t(".group"), @group %> |
  <%= link_to t(".back"), groups_path %>
</div>

app/views/groups/index.html.erb
<h1><%= t(".groups")%>
<% if current_user&.able_to_edit?(:schedule) %>
  <%= link_to bi("plus-square ms-2 text-primary"), new_group_path %>
<% end %>
</h1>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>

app/views/groups/my.html.erb
<%= render "my_group", group: @group %>

<div>
  <%= link_to t(".back"), groups_path %>
</div>

app/views/groups/new.html.erb
<h1> <%= t(".name") %> </h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to t(".back"), groups_path %>
</div>

app/views/groups/show.html.erb
<%= render @group %>

<div>
  <%= link_to t(".back"), groups_path %>
</div>