config/routes.rb
Rails.application.routes.draw do
  root "groups#index"

  resources :groups do
    get :my, on: :collection
    resources :schedules, except: %i[new create destroy] do
      resources :lessons
    end
  end
  resources :subjects, only: [:edit, :update, :new, :create, :destory]
  resources :teachers, only: [:edit, :update, :new, :create, :destory]

  resources :lessons_changes

  resource :week_status, only: [] do
    post :toggle, on: :collection
  end

  resources :events, except: %i[show]
  resources :subscriptions, only: :create
  delete "/subscriptions", to: "subscriptions#destroy"

  get "profile", to: "users#show"
  get "profile/edit", to: "users#edit"
  patch "profile", to: "users#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :subscriptions, dependent: :destroy

  validates :title, presence: true
  validates :title, length: {minimum: 3}
  validates :description, length: {minimum: 30}
  validates :description, length: {maximum: 300}
end

app/models/group.rb
class Group < ApplicationRecord
  after_create :create_schedule
  has_many :schedules, dependent: :destroy
  has_many :lessons_changes, dependent: :destroy
  has_many :users, dependent: :nullify

  private

  def create_schedule
    (1..6).each do |week|
      Schedule.create(group: self, weeks_day: week)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :schedule
  belongs_to :subject
  belongs_to :teacher

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :number, uniqueness: {scope: :schedule_id}, unless: -> { adjacent }
  validates :schedule, presence: true
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validate :adjacent_lesson_uniqueness

  private

  def adjacent_lesson_uniqueness
    return unless adjacent? && schedule.lessons.where(number:, adjacent: true).exists?

    errors.add(:adjacent, "уже есть у урока")
  end
end

app/models/lessons_change.rb
class LessonsChange < ApplicationRecord
  belongs_to :subject
  belongs_to :teacher
  belongs_to :group

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validates :group, presence: true
  validates :group, uniqueness: {scope: [:number, :date]}

  before_validation :set_default_date, on: :create

  private

  def set_default_date
    self.date ||= Date.tomorrow
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, through: :user_roles
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  DAYS_OF_WEEK = {
    1 => "Понедельник",
    2 => "Вторник",
    3 => "Среда",
    4 => "Четверг",
    5 => "Пятница",
    6 => "Суббота"
  }.freeze

  belongs_to :group
  has_many :lessons, dependent: :destroy

  def wday
    DAYS_OF_WEEK[weeks_day]
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3

  belongs_to :group, optional: true
  has_many :subscriptions, dependent: :destroy
  has_many :user_roles
  has_many :roles, through: :user_roles

  def able_to_edit?(model)
    roles.map(&:name).include?(model.to_s)
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/week_status.rb
class WeekStatus < ApplicationRecord
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_group
  before_action :set_schedule, only: %i[show edit update destroy]

  # GET /schedules
  def index
    @schedules = Schedule.preload(lessons: [:subjects, :teachers]).load
  end

  # GET /schedules/1
  def show
  end

  # GET /schedules/new
  def new
    @schedule = @group.schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  def create
    @schedule = @group.schedule.new(schedule_params)

    if @schedule.save
      redirect_to @schedule, notice: "Расписание успешно создано."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /schedules/1
  def update
    if @schedule.update(schedule_params)
      redirect_to @schedule, notice: "Расписнеи успешно обновлено."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /schedules/1
  def destroy
    @schedule.destroy
    redirect_to schedules_url, notice: "Расписание успешно удалено."
  end

  private

  def authorization
    render_forbidden unless current_user&.able_to_edit?(:schedule)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def schedule_params
    params.require(:schedule).permit(:group, :weeks_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def even_week?
    WeekStatus.first_or_create.even_week?
  end

  def bi(icon)
    "<i class=\"bi bi-#{icon}\"></i>".html_safe
  end

  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger if type == :alert
      type = :danger if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert alert-#{type} alert-dismissible fade show mt-3 #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw(""), :type => "button", :class => "btn-close", "data-bs-dismiss" => "alert", "aria-label" => "Close")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schedules/_my_schedule.html.erb
<div class="col-lg-4 col-md-6">
  <div class="card mb-md-4 mb-1">
    <div class="card-body">
      <h4 class="card-title text-center"> <%= schedule.wday %></h4>

      <table class="table">
        <tr>
          <th>№</th>
          <th><%= t('.room') %></th>
          <th><%= t('.subject') %></th>
          <% if current_user&.able_to_edit?(:schedule) %><th></th><% end %>
        </tr>
<% changes = @changes.where(date: Date.tomorrow.beginning_of_week + (schedule.weeks_day - 1)) %>
<% lessons = schedule.lessons.sort_by(&:number)%>
<% before_lessons = changes.where("number < ?", lessons.first&.number) %>
<% before_lessons.each do |change| %>
  <tr>
      <th class="text-danger fw-bold"><%= change.number %></th>
      <th class="text-danger fw-bold"><%= change.room %></th>
      <th class="text-danger fw-bold"><%= change.subject.name %><br>
      <%= change.teacher.name %></th>
    <% if current_user&.able_to_edit?(:change) %>
      <th><%= link_to bi("pencil"), edit_lessons_change_path(id: change)%><br>
      <%= button_to bi("x-square text-danger"), lessons_change_path(id: change), 
      method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')"%></th>
    <% end %>
  </tr>
<% end %>

<% lessons.each.with_index do |lesson, index| %>
  <% next if lesson.adjacent && even_week? || lessons[index+1]&.adjacent && !even_week? %>

  <% change = changes.find_by(number: lesson.number) %>

  <tr>
    <% if change %>
      <th class="text-danger fw-bold"><%= change.number %></th>
      <th class="text-danger fw-bold"><%= change.room %></th>
      <th class="text-danger fw-bold"><%= change.subject.name %><br>
      <%= change.teacher.name %></th>

      <% if current_user&.able_to_edit?(:change) %>
        <th><%= link_to bi("pencil"), edit_lessons_change_path(id: change)%><br>
        <%= button_to bi("x-square text-danger"), lessons_change_path(id: change), 
        method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')"%></th>
      <% end %>
    <% else%>
      <th><%= lesson.number %></th>
      <th><%= lesson.room %></th>
      <th><%= lesson.subject.name %><br>
      <%= lesson.teacher.name %></th>

      <% if current_user&.able_to_edit?(:schedule) %>
        <th><%= link_to bi("pencil"), edit_group_schedule_lesson_path(id: lesson, schedule_id: schedule.id, group_id: schedule.group.id)%><br>
        <%= button_to bi("x-square text-danger"), group_schedule_lesson_path(id: lesson, schedule_id: schedule.id, group_id: schedule.group.id), 
        method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')"%></th>
    <% end %>
    <% end %>
  </tr>
<% end %>

<% last_lesson = lessons.last&.number %>

<% changes.where("number > ?", last_lesson).each do |change| %>
  <tr>
      <th class="text-danger fw-bold"><%= change.number %></th>
      <th class="text-danger fw-bold"><%= change.room %></th>
      <th class="text-danger fw-bold"><%= change.subject.name %><br>
      <%= change.teacher.name %></th>
    <% if current_user&.able_to_edit?(:change) %>
      <th><%= link_to bi("pencil"), edit_lessons_change_path(id: change)%><br>
      <%= button_to bi("x-square text-danger"), lessons_change_path(id: change), 
      method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')"%></th>
    <% end %>
  </tr>
<% end %>

      </table>

      <i class="bi bi- m"></i>
      <% if current_user&.able_to_edit?(:schedule) %>
        <%= link_to bi("plus-square ms-2 text-primary"), new_group_schedule_lesson_path(schedule_id: schedule.id, group_id: schedule.group.id) %>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/_schedule.html.erb
<div class="col-lg-4 col-md-6">
  <div class="card mb-md-4 mb-1">
    <div class="card-body">
      <h4 class="card-title text-center"> <%= schedule.wday %></h4>
        <table class="table">
          <tr>
            <th>№</th>
            <th><%= t('.room') %></th>
            <th><%= t('.subject') %></th>
            <% if current_user&.able_to_edit?(:schedule) %><th></th><% end %>
          </tr>
      <% if params[:actual] %>
        <% lessons = schedule.lessons.sort_by(&:number)%>
        <% lessons.each.with_index do |lesson, index| %>
          <% next if lesson.adjacent && even_week? || lessons[index+1]&.adjacent && !even_week? %>
          <tr>
            <th><%= lesson.number %></th>
            <th><%= lesson.room %></th>
            <th><%= lesson.subject.name %><br>
            <%= lesson.teacher.name %></th>
            <% if current_user&.able_to_edit?(:schedule) %>
              <th><%= link_to bi("pencil"), edit_group_schedule_lesson_path(id: lesson, schedule_id: schedule.id, group_id: schedule.group.id)%><br>
              <%= button_to bi("x-square text-danger"), group_schedule_lesson_path(id: lesson, schedule_id: schedule.id, group_id: schedule.group.id), 
              method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')"%></th>
            <% end %>
          </tr>
        <% end %>
      <% else %>
        <% schedule.lessons.sort_by(&:number).each do |lesson| %>
        <tr>
          <th><%= lesson.number unless lesson.adjacent%></th>
          <th><%= lesson.room %></th>
          <th><%= lesson.subject.name %><br>
          <%= lesson.teacher.name %></th>
          <% if current_user&.able_to_edit?(:schedule) %>
            <th><%= link_to bi("pencil"), edit_group_schedule_lesson_path(id: lesson, schedule_id: schedule.id, group_id: schedule.group.id)%><br>
            <%= button_to bi("x-square text-danger"), group_schedule_lesson_path(id: lesson, schedule_id: schedule.id, group_id: schedule.group.id), 
            method: :delete, class: "button", onclick: "return confirm('#{t(".delete_confirm")}')"%></th>
          <% end %>
        </tr>
        <% end %>
      <% end %>
      </table>
      <i class="bi bi- m"></i>
      <% if current_user&.able_to_edit?(:schedule) %>
        <%= link_to bi("plus-square ms-2 text-primary"), new_group_schedule_lesson_path(schedule_id: schedule.id, group_id: schedule.group.id) %>
      <% end %>
    </div>
  </div>
</div>

app/views/schedules/index.html.erb
<h1><%= t(".schedules")%></h1>

<div id="schedules">
  <h3 class="text-center">
    <strong>Group:</strong>
    <%= @group.name %>
  </h3>

  <div class="row">
    <% schedules = @schedules.where(group: @group)%>
    <% schedules.each do |schedule| %>
      <%= render schedule %>
    <% end %>
  </div>
</div>