config/routes.rb
Rails.application.routes.draw do
  root "groups#index"

  resources :groups do
    get :my, on: :collection
    resources :schedules, except: %i[new create destroy] do
      resources :lessons
    end
  end
  resources :subjects, only: [:edit, :update, :new, :create, :destory]
  resources :teachers, only: [:edit, :update, :new, :create, :destory]

  resources :lessons_changes

  resource :week_status, only: [] do
    post :toggle, on: :collection
  end

  resources :events, except: %i[show]
  resources :subscriptions, only: :create
  delete "/subscriptions", to: "subscriptions#destroy"

  get "profile", to: "users#show"
  get "profile/edit", to: "users#edit"
  patch "profile", to: "users#update"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :subscriptions, dependent: :destroy

  validates :title, presence: true
  validates :title, length: {minimum: 3}
  validates :description, length: {minimum: 30}
  validates :description, length: {maximum: 300}
end

app/models/group.rb
class Group < ApplicationRecord
  after_create :create_schedule
  has_many :schedules, dependent: :destroy
  has_many :lessons_changes, dependent: :destroy
  has_many :users, dependent: :nullify

  private

  def create_schedule
    (1..6).each do |week|
      Schedule.create(group: self, weeks_day: week)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :schedule
  belongs_to :subject
  belongs_to :teacher

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :number, uniqueness: {scope: :schedule_id}, unless: -> { adjacent }
  validates :schedule, presence: true
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validate :adjacent_lesson_uniqueness

  private

  def adjacent_lesson_uniqueness
    return unless adjacent? && schedule.lessons.where(number:, adjacent: true).exists?

    errors.add(:adjacent, "уже есть у урока")
  end
end

app/models/lessons_change.rb
class LessonsChange < ApplicationRecord
  belongs_to :subject
  belongs_to :teacher
  belongs_to :group

  validates :number, presence: true
  validates :number, numericality: {only_integer: true}
  validates :number, numericality: {greater_than: 0}
  validates :number, numericality: {less_than: 8}
  validates :subject, presence: true
  validates :teacher, presence: true
  validates :room, presence: true
  validates :room, numericality: {greater_than: 99}
  validates :room, numericality: {less_than: 1000}
  validates :group, presence: true
  validates :group, uniqueness: {scope: [:number, :date]}

  before_validation :set_default_date, on: :create

  private

  def set_default_date
    self.date ||= Date.tomorrow
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, through: :user_roles
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  DAYS_OF_WEEK = {
    1 => "Понедельник",
    2 => "Вторник",
    3 => "Среда",
    4 => "Четверг",
    5 => "Пятница",
    6 => "Суббота"
  }.freeze

  belongs_to :group
  has_many :lessons, dependent: :destroy

  def wday
    DAYS_OF_WEEK[weeks_day]
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3

  belongs_to :group, optional: true
  has_many :subscriptions, dependent: :destroy
  has_many :user_roles
  has_many :roles, through: :user_roles

  def able_to_edit?(model)
    roles.map(&:name).include?(model.to_s)
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/week_status.rb
class WeekStatus < ApplicationRecord
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= t('.title') %></title>
    <link rel="icon" type="image/x-icon" href=<%=asset_path('favicon.ico')%>>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container-md">
      <nav class="navbar navbar-expand-lg bg-light rounded mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <img src=<%=asset_path('favicon.ico')%> alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
            <%= t('.title') %>
          </a>
          
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarsExample09" style="">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to t('.groups'), groups_path, class: 'nav-link' %>
              </li>
              <% unless current_user.nil? || current_user.id.nil? || current_user&.group_id.nil? %>
                <li class="nav-item">
                  <%= link_to t('.schedules'), my_groups_path, class: 'nav-link' %>
                </li>
              <% end %>
                <%= link_to t('.changes'), lessons_changes_path, class: 'nav-link', data: { turbo: "false" } %>
              </li>
              <li class="nav-item">
                <%= link_to t('.events'), events_path, class: 'nav-link'%>
              </li>
            </ul>

              <% if current_user&.able_to_edit?(:schedule) %>
              <%= form_with url: toggle_week_status_path, method: :post, remote: true do |form| %>
                <%= form.button bi("arrow-down-up text-primary"), class: "btn", onclick: "return confirm('#{t(".change_week")}')" %>
              <% end %>
              <% end %>

              <div class="week me-2 <%= even_week? ? 'even-week' : 'odd-week' %>">
                <div class="square" data-tooltip="">
                  <div class="half top-half <%= even_week? ? 'active' : '' %>" title="<%= even_week? ? 'Текущая неделя: Первая' : 'Текущая неделя: Вторая' %>"></div>
                  <div class="half bottom-half <%= even_week? ? '' : 'active' %>" title="<%= even_week? ? 'Текущая неделя: Первая' : 'Текущая неделя: Вторая' %>"></div>
                </div>
              </div>

              <% if current_user.nil? %>
              <%= link_to t('.login'), rodauth.login_path, class: 'btn btn-outline-primary' %>
              <% else %>
              <%= link_to t('.profile'), profile_edit_path, class: 'btn btn-outline-primary me-1' %>
              <%= form_with url: rodauth.logout_path, method: :post, data: { turbo: false } do |form| %>
                <% if rodauth.features.include?(:active_sessions) %>
                  <%= form.check_box rodauth.global_logout_param, id: "global-logout", include_hidden: false %>
                  <%= form.label "global-logout", rodauth.global_logout_label %>
                <% end %>
                <%= form.submit rodauth.logout_button, class: "btn btn-outline-danger", onclick: "return confirm('#{t(".exit_confirm")}')"  %>
              <% end %>
              <% end %>

          </div>
        </div>
      </nav>

      <div class="container">
        <%= bootstrap_flash %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>